Github pages deployment hotfix.

diff --git a/.github/workflows/update-github-pages.yml b/.github/workflows/update-github-pages.yml
--- a/.github/workflows/update-github-pages.yml
+++ b/.github/workflows/update-github-pages.yml
@@ -11,40 +11,43 @@ jobs:
 
     steps:
       - name: Github pages
-        uses: actions/checkout@master
+        uses: actions/checkout@v2
         with:
           repository: rszewczyk2204/rszewczyk2204.github.io
           ref: refs/heads/main
 
+      - name: Clone repo
+        run: |
+          git clone ${{ secrets.PAGES_REPO_GIT }}
+          cd ${{ secrets.REPO_NAME }}
+
       - name: Put entry in github pages
         run: |
-            git clone ${{ secrets.PAGES_REPO_GIT }}
-            cd ${{ secrets.REPO_NAME }}
-            if ! grep -q '<a href="#" class="repo-link">docker-images</a>' index.html; then
-            echo "Repo entry not found, adding it..."
-            sed -i '/<section class="repos">/,/<\/section>/ s~<\/section>~ \
-                        <div class="repo-item"> \
-                            <h4 class="h4"><a href="https://github.com/rszewczyk2204/docker-images" class="repo-link">docker-images</a></h4> \
-                            <button class="expand-repo-button" data-expand-button> \
-                                <span>docker-images</span> \
-                                <ion-icon name="chevron-down"></ion-icon> \
-                            </button> \
-                            <div data-expand-info="docker-images" class="expand-repo-info"> \
-                                <span>Repo containing docker images to run more advanced GitHub actions. \
-                                </span> \
-                            </div> \
-                        </div> \
-                        <div class="separator"></div> \
-                    </section>~' index.html 
-            else
-              echo "Repo entry already exists."
-            fi
-            git config user.name "${{ secrets.GIT_USERNAME }}"
-            git config user.email "${{ secrets.GIT_USER_EMAIL }}"
-            git add .
-            git commit -m "Add docker-image entry"
-            git push origin main
-
+          if ! grep -q '<a href="#" class="repo-link">docker-images</a>' index.html; then
+          echo "Repo entry not found, adding it..."
+          sed -i '/<section class="repos">/,/<\/section>/ s~<\/section>~ \
+                      <div class="repo-item"> \
+                          <h4 class="h4"><a href="https://github.com/rszewczyk2204/docker-images" class="repo-link">docker-images</a></h4> \
+                          <button class="expand-repo-button" data-expand-button> \
+                              <span>docker-images</span> \
+                              <ion-icon name="chevron-down"></ion-icon> \
+                          </button> \
+                          <div data-expand-info="docker-images" class="expand-repo-info"> \
+                              <span>Repo containing docker images to run more advanced GitHub actions. \
+                              </span> \
+                          </div> \
+                      </div> \
+                      <div class="separator"></div> \
+                  </section>~' index.html 
+          else
+            echo "Repo entry already exists."
+          fi
+          git diff --exit-code || { echo "There are no changes in the working directory"; exit 1; }
+          git config user.name "${{ secrets.GIT_USERNAME }}"
+          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
+          git add .
+          git commit -m "Add docker-image entry"
+          git push origin main
 
       - name: Cleanup
         run: |
